language: objective-c
before_install:
    - brew update
    - brew uninstall xctool && brew install xctool
install: cd ExampleBasecamp; pod install; cd ..
script:
    - pod spec lint 
    - xctool -project Example/DrawReport.xcodeproj -scheme DrawReport -sdk iphonesimulator ARCHS=i386 ONLY_ACTIVE_ARCH=NO build 
    - xctool -workspace ExampleBasecamp/DrawReportBasecamp.xcworkspace -scheme DrawReportBasecamp -sdk iphonesimulator ARCHS=i386 ONLY_ACTIVE_ARCH=NO build
